== FAQ API
=== 전체 조회

operation::faq-api-controller-test/find-all[snippets='curl-request,http-request,http-response,response-fields']

=== 단건 조회

operation::faq-api-controller-test/find-by-id[snippets='curl-request,http-request,http-response,response-fields']

=== 존재하지 않는 ID로 조회

- 요청: `GET /api/faqs/{faqId}`
- 설명: 존재하지 않는 FAQ 요청 시, `error` View 반환
- Path Parameters: `faqId` (Long): 조회할 FAQ의 ID
- View name: `error`
- Model attributes: `error`

=== 저장

operation::faq-api-controller-test/save[snippets='curl-request,http-request,http-response']

=== 저장 시 질문 누락 예외

operation::faq-api-controller-test/invalid-question-to-save[snippets='curl-request,http-request,http-response,response-fields']

=== 저장 시 질문 길이 제한 예외

operation::faq-api-controller-test/invalid-question-length-to-save[snippets='curl-request,http-request,http-response,response-fields']

=== 저장 시 답변 누락 예외

operation::faq-api-controller-test/invalid-answer-to-save[snippets='curl-request,http-request,http-response,response-fields']

=== 저장 시 답변 길이 제한 예외

operation::faq-api-controller-test/invalid-answer-length-to-save[snippets='curl-request,http-request,http-response,response-fields']

=== 저장 시 카테고리 누락 예외

operation::faq-api-controller-test/invalid-category-to-save[snippets='curl-request,http-request,http-response,response-fields']

=== 수정

operation::faq-api-controller-test/update[snippets='curl-request,http-request,http-response']

=== 존재하지 않는 ID로 수정

- 요청: `PUT /api/faqs/{faqId}`
- 설명: 존재하지 않는 FAQ 수정 요청 시, `error` View 반환
- Path Parameters: `faqId` (Long): 수정할 FAQ의 ID
- View name: `error`
- Model attributes: `error`

=== 수정 시 질문 누락 예외

operation::faq-api-controller-test/invalid-question-to-update[snippets='curl-request,http-request,http-response,response-fields']

=== 수정 시 질문 길이 제한 예외

operation::faq-api-controller-test/invalid-question-length-to-update[snippets='curl-request,http-request,http-response,response-fields']

=== 수정 시 답변 누락 예외

operation::faq-api-controller-test/invalid-answer-to-update[snippets='curl-request,http-request,http-response,response-fields']

=== 수정 시 답변 길이 제한 예외

operation::faq-api-controller-test/invalid-answer-length-to-update[snippets='curl-request,http-request,http-response,response-fields']

=== 수정 시 카테고리 누락 예외

operation::faq-api-controller-test/invalid-category-to-update[snippets='curl-request,http-request,http-response,response-fields']

=== 삭제

operation::faq-api-controller-test/remove[snippets='curl-request,http-request,http-response']

=== 존재하지 않는 ID로 삭제

- 요청: `DELETE /api/faqs/{faqId}`
- 설명: 존재하지 않는 FAQ 삭제 요청 시, `error` View 반환
- Path Parameters: `faqId` (Long): 삭제할 FAQ의 ID
- View name: `error`
- Model attributes: `error`