== 공지사항 API
=== 전체 조회

operation::notice-api-controller-test/find-all[snippets='curl-request,http-request,http-response,response-fields']

=== 단건 조회

operation::notice-api-controller-test/find-by-id[snippets='curl-request,http-request,http-response,response-fields']

=== 존재하지 않는 ID로 조회

- 요청: `GET /api/notices/{noticeId}`
- 설명: 존재하지 않는 공지사항 요청 시, `error` View 반환
- Path Parameters: `noticeId` (Long): 조회할 공지사항의 ID
- View name: `error`
- Model attributes: `error`

=== 저장

operation::notice-api-controller-test/save[snippets='curl-request,http-request,http-response']

=== 저장 시 제목 누락 예외

operation::notice-api-controller-test/invalid-title-to-save[snippets='curl-request,http-request,http-response,response-fields']

=== 저장 시 제목 길이 제한 예외

operation::notice-api-controller-test/invalid-title-length-to-save[snippets='curl-request,http-request,http-response,response-fields']

=== 저장 시 내용 누락 예외

operation::notice-api-controller-test/invalid-content-to-save[snippets='curl-request,http-request,http-response,response-fields']

=== 수정

operation::notice-api-controller-test/update[snippets='curl-request,http-request,http-response']

=== 존재하지 않는 ID로 수정

- 요청: `PUT /api/notices/{noticeId}`
- 설명: 존재하지 않는 공지사항 수정 요청 시, `error` View 반환
- Path Parameters: `noticeId` (Long): 수정할 공지사항의 ID
- View name: `error`
- Model attributes: `error`

=== 수정 시 제목 누락 예외

operation::notice-api-controller-test/invalid-title-to-update[snippets='curl-request,http-request,http-response,response-fields']

=== 수정 시 제목 길이 제한 예외

operation::notice-api-controller-test/invalid-title-length-to-update[snippets='curl-request,http-request,http-response,response-fields']

=== 수정 시 내용 누락 예외

operation::notice-api-controller-test/invalid-content-to-update[snippets='curl-request,http-request,http-response,response-fields']

=== 삭제

operation::notice-api-controller-test/remove[snippets='curl-request,http-request,http-response']

=== 존재하지 않는 ID로 삭제

- 요청: `DELETE /api/notices/{noticeId}`
- 설명: 존재하지 않는 공지사항 삭제 요청 시, `error` View 반환
- Path Parameters: `noticeId` (Long): 삭제할 공지사항의 ID
- View name: `error`
- Model attributes: `error`